
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-6pm-3
owner: ucsb-cs156-w24
repo_name: team01-w24-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBh72PQ","is_bot":false,"login":"andyjin1","name":"Andy Jin"},"headRefName":"Andy-Zipcode-Controller","number":27,"title":"Added Zipcode Controller and tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-3/pull/27"},{"author":{"id":"U_kgDOBX3m_g","is_bot":false,"login":"welaalice","name":"Towela Phiri"},"headRefName":"Towela-Tides-Controller","number":24,"title":"Add tides controller and tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-3/pull/24"},{"author":{"id":"MDQ6VXNlcjg2NzQzODY1","is_bot":false,"login":"Jenniebn","name":"Jennie Wu"},"headRefName":"JW-Joke-Controller","number":23,"title":"Jw joke controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-3/pull/23"},{"author":{"id":"U_kgDOBX3m_g","is_bot":false,"login":"welaalice","name":"Towela Phiri"},"headRefName":"Towela-Tides","number":20,"title":"Add Tides Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-3/pull/20"},{"author":{"id":"U_kgDOB3CMjQ","is_bot":false,"login":"jenniferlopez17","name":""},"headRefName":"Jennifer-Location","number":19,"title":"Add Location Service and Tests #8","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-3/pull/19"}]
